site:
  build: .
  ports :
   - "80:80"
  volumes:
   - /Users/stant02/Documents/projects/sinsunsisal:/var/www/html/
  links:
   - database
phpmyadmin:
   image: phpmyadmin/phpmyadmin
   ports :
    - "8080:80"
   environment:
    - MYSQL_USERNAME=root
    - MYSQL_PASSWORD=password
   links:
    - database:db
database:
  image: mysql:5.5
  ports:
   - "3306:3306"
  environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=mysite
     - MYSQL_USER=mysite
     - MYSQL_PASSWORD=password
